name: First WorkFlow 
on: workflow_dispatch
jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: this is step 1
              run: echo Creating a yml file manually
            - name: this is step 2
              run: |
                  echo line 1
                  echo line 2