name: events demo!
on:
    push:
        branches:
            -main
        paths:
            -'.github/workflows/02*.yml'
jobs:
    events-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: print helloworld
              run: echo "Hello world!!!!!"
            - name: output of a event data
              run: echo  "${{ toJson(github.event)}}"
            - name: Get Code
              run: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Test Code
              run: npm run test:envTest
            # - name:
            #   run: